/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package estay;

import javax.swing.SwingUtilities;

import estay.database.DatabaseConnection;
import estay.ui.HotelCheckInCheckOutUI;

public class App {
    public String getGreeting() {
        DatabaseConnection connection = new DatabaseConnection();
        
        return connection + "Hello World!";
    }

    public static void main(String[] args) {
        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                HotelCheckInCheckOutUI ui = new HotelCheckInCheckOutUI();
                ui.setVisible(true);
            }
        });
    }
}